#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

## build
FROM golang:1.23.4-bookworm AS go_base
ARG TARGETARCH
WORKDIR /app

ENV GOPROXY=direct
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod,id=${TARGETARCH} \
    --mount=type=cache,target=/root/.cache/go-build,id=${TARGETARCH} \
    go mod download
RUN go mod download

RUN --mount=type=cache,target=/go/pkg/mod,id=${TARGETARCH} \
    --mount=type=cache,target=/root/.cache/go-build,id=${TARGETARCH} \
    go install honnef.co/go/tools/cmd/staticcheck@2024.1.1 && \
    go install github.com/securego/gosec/v2/cmd/gosec@v2.21.4

FROM go_base AS go_eks_base
FROM go_base AS go_lambda_base
