#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0
FROM amazonlinux:2023 as build_image

RUN dnf install aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel -y

######## app image ########
FROM build_image as pod_image

RUN dnf install python3 awscli jq -y
